Irish-Film-Institute/IFIscripts

- ififuncs.py
Ok, so it turned out that the issue seems to just be that DV was not in the list of file types that ififuncs uses to generate a list of files to process. I only did some basic testing but blaa.csv had actual tech metadata, so @hyz2993  can you do better testing, like running the batchaccession job and seeing if this is enough to fix the issue? Still have zero idea why it didn't just crash for Yujing and instead just make an incomplete CSV. Perhaps there's more to this than meets the eye..
> ififuncs - add DV to recursive_file_list()

- scripts/sipcreator.py
**Background**
a manifest created by sipcreator.py with special collection material will have both parts of the previous files and the current files IF THE PREVIOUS SIPCREATOR.PY STOPPES DURING PROCESSING, which will cause the current validation to get wrong (files shown in the manifest are not in the local directory).
The screenshot above is the "moveit_manifest" folder on the desktop. It is like a transit station (sorry I think I used the wrong word in the meeting) for scripts making manifest. The script will make the manifest here. At the end of running, the script will copy it to the target folder (ie. sip folder) and move it to the "old_manifests" folder as shown in that folder.
So "old_manifests" stores manifests generated during the pre-existed sipcreator.py or other scripts need …
> sipcreator.py - add atexit.register for remaining manifest in the desktop manifest dir

- scripts/batchaccession.py
- scripts/ififuncs.py
> batchaccession.py, ififuncs.py - utf-8 fixes

- scripts/sipcreator.py
This pull request is a result of issue #48 
According to clairmeta/dcp.py check module
```self.log.info("Check report:\n\n" + report.pretty_str())```
`report.pretty_str()` stores the report including the result, warnings, errors, etc.
Used this $var to get reports and write into the text file.
Created `$oe_clairmeta_outcome_$datetime.txt` to exporting the report.
Also added the parameter `txt_name_source` in the `process_dcp` module to transfer the text name.
> sipcreator.py - clairmeta output to text file

- scripts/as11fixity.py
`AS11FIXITY.PY` Update:
1. Add block for *SIP/metadata/supplement/_MediaConchReport.xml* as it is recognised by the script by mistake.
Before:
| ID | oe | accessionnumber | files_count | directory_count | Filename | Series_Title | Prog_Title | Episode_Number | Md5_From_Xml | Md5_from_Mxf | Checksum_Result |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| oe12345 | oe12345| | 15 | 5 | RG-MP-GW001.mxf_MediaConchReport.xml | error | error | error | error | error | CHECKSUM DOES NOT MATCH! |
| oe12345 | oe12345| | 15 | 5 | RG-MP-GW001.mxl | $Title | Episode 1 | Episode 1 | cdc686ddb1a9f19c5b7d01a59ae7e121 | cdc686ddb1a9f19c5b7d01a59ae7e121 | CHECKSUM MATCHES! |
Now (the first row won't appear):
| ID | oe | accessionnumber | files_count | directory_count | Filename …
> as11fixity.py - add block for -MediaConchReport.xml, update dir walking structure, add  checksums display in the terminal

- scripts/structure_check.py
A new script for printing directory tree of each information package in a batch.
``````
usage: structure_check.py [-h] -i I
Directory tree of each information package in a batch. Written by Yazhou He.
options:
-h, --help  show this help message and exit
-i I        full path of a batch of SIPs/AIPs/AIP shells
``````
for system has built-in tool `tree`:
``````
AIP     D:\test\aaa1234
Folder PATH listing for volume Internal Storage
Volume serial number is 2E27-9167
D:\TEST\AAA1234
└───6ebb08ed-e1ac-4a64-8ab2-87f28d060dfe
└───logs
*Type anything and enter if it is a failure.
*Press enter if it a pass.
-----
All information packages have passed check!
-----
Here are the failed information packages you just marked out:
D:\test\aaa1234
``````
for system doesn't have built-in tool `tree`:
`````` …
> structure_check.py - new script

- docs/usage.rst
- pyproject.toml
- scripts/merge_csv.py
- setup.py
Features: Merge and sorted csvs.
Terminal view:
```
CSV Title: entry number | accession number | date acquired | date accessioned | acquired from | acquisition method | simple name; basic description; identification; historical information | notes
Select the index of the name you want to use.
Type in the name if not in the list:
1. flimo_csv_merged
2. pbcore_merged
3. sorted_merged
4. helper_register_merged
4
User selected: helper_register_merged
-
Are you really sure? - The name will be:
2023-08-16T12_20_45_helper_register_merged.csv
enter Y or N
n
Select the index of the name you want to use.
Type in the name if not in the list:
1. flimo_csv_merged
2. pbcore_merged
3. sorted_merged
4. helper_register_merged
helper_register_merged_test
User typed: helper_register_merged_test
-
Are you …
```
> merge_csv.py - new scripts - for merging csvs like helper_register

- scripts/check_register.py
- scripts/get_ps_list.py
Two new Python scripts for checking if the records in the digital accession register/helper register match the files' logs in preservation storage.
`get_ps_list.py` is to get a CSV of all AIPs in preservation storage with accession number and object entry number. the information is got from the sip_log.log in each AIP/.../logs/.
`check_register.py` is to check any mismatch in the digital accession register/helper register by comparing the same accession number but different objects entry number, and the same object entry number but different accession number.
The scripts have been tested and applied in a project in the closing steps.
> get_ps_list.py, check_register.py - new scripts

- scripts/sipcreator.py
Add `package_update.py` to update clairmeta output text file checksum and path into SIP manifest
> sipcreator.py -dcp - fixed bug clairmeta output text file doesn't update in SIP manifest

- scripts/prores.py
Add args.xq for ProRes 4444XQ output
['ffmpeg', '-i', input, '-c:a', 'copy', '-c:v', 'prores', '-map', '0:a?', '-map', '0:v', '-profile:v', '5', '-pix_fmt', 'yuv444p10le', output]
> prores.py - add args.xq for ProRes 4444XQ option

- scripts/bitc.py
This is changed as the current command for ffmpeg 6.0 will burn the watermark or timecode in the video stream and create a new clean video track.
The change has been tested that it remains the only video track just like before.
> bitc.py - changed ffmpeg -filter_complex to -vf

- scripts/bitc.py
Original code: `timecode_option = "drawtext=...:timecode=%s:...`
Error found:
```
[Parsed_drawtext_0 @ 0000027851e9b480] Unable to parse timecode, syntax: hh:mm:ss[:;.]ff
[AVFilterGraph @ 0000027852553a40] Error initializing filter 'drawtext' with args 'fontfile=C\:\\Windows\\Fonts\\arial.ttf:fontcolor=white:fontsize=20.0:timecode=01:00:00:00:rate=15/1:boxcolor=0x000000AA:box=1:x=(w-text_w)/2:y=h/1.2'
Error reinitializing filters!
Failed to inject frame into filter network: Invalid data found when processing input
Error while processing the decoded data for stream #0:0
```
Solution - add quotes for timecode value: `timecode_option = "drawtext=...:timecode='%s':...`
ref commit 621ae4a
---
Error found: #75 'bitc broken on mac?'
Solution - move quotes to `timecode_test` for win32
```
elif …
```
> bitc.py timecode error fix

- scripts/batchmakeshell.py
'batchmakeshell.py -dcdm' will change the package trigger from 'aaa' to 'oe'.
> batchmakeshell.py - add dcdm option for backup DCDM SIP without objects

- pyproject.toml
- scripts/seq2ffv1.py
add `clean_start()` for every `subprocess.call('rawcooked',...)` to avoid occasionally RawCooked freezing during script running.
It checks whether 'rawcooked' is in the pid list and kill it every time before run `subprocess.call()`.
This has been tested on Mac and worked fine.
Layout:
RAWcooked.exe process is in the back stage. Terminating it...
RAWcooked.exe process has been terminated. Ready to start running.
Ready for a clean start:
['rawcooked', '--check-padding', ......]
> seq2ffv1.py - check rawcooked process before run

- scripts/bitc.py
bitc.py has update command for supporting from ffmpeg 5.1.2 (used by IFI Irish Film Archive before) to 6.0 and above version.
Fixed and merged the problem of escape character in different OS.
Lower version will meet errors from ``fontfile``, ``text and textfile``, or ``fontcolor``, etc. but they should all be a version problem.
Also update for Python 3.12, which changes ``SyntaxWarning: invalid escape sequence '\:'`` from ``DeprecationWarnings`` to ``SyntaxWarning`` and prints in the terminal. (https://docs.python.org/3/whatsnew/3.12.html#other-language-changes)
> bitc.py - update ffmpeg drawtext for ffmpeg 6.0+

- scripts/as11fixity.py
```
as11fixity.py -h
usage: as11fixity.py [-h] input
Validates AS-11 UK DPP mxf file(s) by comparing file checksum from information package manifest and DPP xml <MediaChecksumValue>.
positional arguments:
input       An AS-11 package or the parent folder of AS-11 packages
options:
-h, --help  show this help message and exit
```
> as11fixity.py - make input as an argument

- scripts/bitc.py
Fixed:
- logo option requires `-filter_complex` option to replace `-vf`.
```
[vf#0:0 @ 0x600003549680] Simple filtergraph 'overlay=main_w-overlay_w-5:5' was expected to have exactly 1 input and 1 output. However, it had 2 input(s) and 1 output(s). Please adjust, or use a complex filtergraph (-filter_complex) instead.
[vost#0:0/libx264 @ 0x126e08510] Error initializing a simple filtergraph
Error opening output file /Volumes/......_h264.mov.
Error opening output files: Invalid argument
```
- ffmpeg cannot locate stream from multiple streams (video and timecode mostly) in the input for overlay.
```
[fc#0 @ 0x600001824000] Cannot find a matching stream for unlabeled input pad overlay
Error binding filtergraph inputs/outputs: Invalid argument
```
- Output is generated with two video streams: …
> bitc.py - ffmpeg command fixed for logo option

- pyproject.toml
- scripts/dcdm_helperpbcore.py
- setup.py
This script is to generate a PBCore-like technical record helper csv.
It ingests metadata required in the IFI Archive DCDM workflow.
As the DCDM objects are compressed in the package, the metadata is generated from AIP/./metadata/supplemental/..._source_mediainfo.xml, AIP/./logs/.../log, and AIP/./metadata/AF...filmographic.csv.
The script has been tested that can import all ingested metadata into a technical record in the database.
> dcdm_helperpbcore.py - new script for creating pbcore-like techncial record helper csv

- scripts/batchaipcreator.py
Issue: the non-breaking space character `\xa0` cause the error when transferring filmographic number, which will escape the whole line of the record.
Fix: add a replacement function to prevent from that
> batchaipcreator.py - add func to replace non-breaking space from online sheet for filmo number

- scripts/bitc.py
This has been tested with the case display aspect ratio is 4:3 and storage aspect ratio is 16:9, which causes the logo shaped.
> bitc.py - dynamic watermark scale for the case PAR (pixel aspect ratio) is not 1 & position
