Irish-Film-Institute/IFIscripts

ififuncs.py, setup.py
update user list, add make_mediaconch.py in setup.py list, update version number to 2022.10.06.1
=> update ififuncs.py/user_list & setup.py/add_mediaconch.py_&_update_version_num

setup.py
emergency fixed - sorry @kieranjol Kieran I miss a ',' in the scripts array in setup.py. Stupid mistake...
=> fix scripts=[...make_mediaconch.py,...] in the list

ififuncs.py, setup.py
update `eventDetail = .py ifiscripts installed from pypi - Version`
add pip show ifiscripts
remove CRLF
reformat log
update version number
=> update `eventDetail = .py ifiscripts installed from pypi - Version`

setup.py
@kieranjol please review the code
=> + as11fixity.py -> setup.py/scripts[] && update version number

scripts/massqc.py
massqc being weird without python3 shebang
=> massqc - adds python3 shebang

scripts/strongbox_fixity.py
=> Update strongbox_fixity.py - utf-8 fixes

scripts/ififuncs.py
Replace ( is ) with ( == ) and ( is not ) with ( != )
=> Update ififuncs.py - Syntax (Python 3.8+)

scripts/ififuncs.py
Updated get_user list to include current staff working with the scripts
=> ififuncs.py: get_user list updated for current staff

scripts/seq2ffv1.py
This update has been tested and applied for the project
=> seq2ffv1.py - update rawcooked command line

scripts/ififuncs.py
Ref #38
This has been tested with:
instance | description | result
-- | -- | --
0 | not the start number | repeat asking
-1 | index for end of the list | repeat asking
10 | beyond length | repeat asking
99 | way beyond length | repeat asking
9 | last index in the list | return correct user
1 | first index in the list | return correct user
Layout
```
**** Who are you?
Press the index (ie. 1)
1.      Allison McGrail
2.      Caroline Crowther
3.      Emma Battlebury
4.      Gavin Martin
5.      Mark Keleghan
6.      Niall Anderson
7.      Raelene Casey
8.      Raven Cooke
9.      Yazhou He
(User list was last updated on 2023-05-23)
9
User selected: Yazhou He
```
=> ififuncs.py - get_user() update structure

scripts/batchaccession.py
=> Update batchaccession.py - utf-8 fixes

scripts/batchaipcreator.py, scripts/ififuncs.py
ififuncs.py
1. index won't print to pbcore
2. update and re-order terms
batchaipcreator.py
1. update index value for reproduction option
Prints in terminal
```
**** What is the type of acquisition? - This will not affect Reproductions that have been auto-detected.
Press 1,2,3,4,5,6
1. Deposit
2. Deposit via overarching agreements
3. Donation
4. Reproduction
5. Purchased for collection
6. Unknown at present
```
=> ififuncs.py, batchaipcreator.py - update acquisition(deposit) list

README.rst, docs/usage.rst, film_scan_aip_documentation.txt, legacy_scripts/revtmd.py, scripts/accession_register.py, scripts/aipcreator.py, scripts/batchaipcreator.py, scripts/batchmakeshell.py, scripts/deletefiles.py, scripts/ififuncs.py, scripts/loopline_repackage.py, scripts/makefolders.py, scripts/makepbcore.py, scripts/order.py, scripts/sipcreator.py
terms correction for "aip/accession"
=> terms correction

pyproject.toml
This has been tested by test - Pypi. Meanwhile, setup.py will be kept in case of any potential bugs.
=> Pyproject.toml - followed by pip requirement

docs/usage.rst, scripts/ififuncs.py, scripts/masscopy.py
Changed out of date references
=> Tiny update to documentation and comments: moveit.py -> copyit.py

docs/usage.rst, scripts/lossy_check.py
New script for checking losslessness for a batch of sipped image sequence objects.
```
usage: lossy_check.py [-h] -i I
Losslessness check for a batch of sipped image sequence objects (SIPs/AIPs/AIP shells). Written by Yazhou He.
options:
-h, --help  show this help message and exit
-i I        full path of a batch of SIPs/AIPs/AIP shells
```
```
AIP aaa1234 found in the source directory
AIP shell aaa5678_shell found in the source directory
SIP oe12345 found in the source directory
aaa1234:        lossless
aaa5678_shell:  lossy
oe12345:        lossless
```
=> lossy_check.py - new scripts

scripts/batchmakeshell.py, scripts/getaips.py, scripts/getdip.py
Usage:
```
usage: getaips.py [-h] -t T -n N [N ...] -i I -o O
Get shells, proxies, and mezzanines from Rackstation by accession number.
Written by Yazhou He.
optional arguments:
-h, --help            show this help message and exit
-t T, -type T         type of required DIP: shell, proxy, mezz
-n N [N ...], -number N [N ...]
required accession numbers, can be more than one
-i I, -input I        path of the root of rackstation drive including
shell/proxy/mezz
-o O, -output O       full path of output directory
```
Checking input directory for the required type
```
['aaa3559', 'aaa7002']
CANNOT found directory for proxy! Check input!
['aaa3559', 'aaa7002']
Found directory for proxy: /Volumes/Browse_Store/clean_proxies
```
Getting path of the DIP with required accession numbers in required …
=> getdip.py - new scripts for getting shells/proxies/mezzanines by accession numbers

scripts/package_update.py
Remove special characters and spaces in the objects' filenames and replace to '_'
The script has been tested, md5 manifest and sha512 manifest, and log files have been updated.
Terminal layout
```
#package_update.py -rename S:\batchsc_organisepy\angelas_christmas
2023-09-26 14:30:30,217 - Clairmeta - WARNING - Missing dependency : sox.exe
Namespace(i=None, new_folder=None, rename=True, input='S:\\batchsc_organisepy\\angelas_christmas', user=None, copy=False)
**** Who are you?
Enter the number before your name (ie. 1)
1. Allison McGrail
2. Amy Mitchell
3. Cody Farren
4. Emma Battlebury
5. Gavin Martin
6. Leanne Bell
7. Mark Keleghan
8. Matheus Almeida
9. Niall Anderson
10. Raelene Casey
11. Raven Ó Cuacaċ
12. Yazhou He
(User list was last updated on 2023-09-22)
12
User selected: Yazhou He …
```
=> package_update.py - new feature 

scripts/batchvalidate.py
Add args.sip for validation SIPs
Add final results at the end of the data as well as a output text file
output text file:
```
Text created time: 2023-09-27 12:11:34 
Script User: yazhou.he 
batchvalidate.py report
SUCCESS - S:\2_existing_sip\artist_and_the_wall_of_death_the\7775893c-634c-4970-8611-fc57e2eef082_manifest.md5 
SUCCESS - S:\2_existing_sip\ballybraddan_series_2\214930b4-07f7-4cad-b60d-6aa9fcfdf16b_manifest.md5 
SUCCESS - S:\2_existing_sip\ballymurphy_precedent_the\73df550f-c61f-497a-bd1d-17d50cbe9a59_manifest.md5 
SUCCESS - S:\2_existing_sip\ballywalter\019c46eb-4643-4c65-8d5a-4aaef13c2ec8_manifest.md5 
FAILURE - S:\2_existing_sip\barber\06210528-9f97-490f-803e-10e31f1bf21d_manifest.md5 
SUCCESS - S:\2_existing_sip\bardo\737d8f33-aab1-4fc0-a562-192ae675a0e7_manifest.md5 …
```
=> batchvalidate.py - new features

scripts/package_update.py
Bug found when running `package_update.py -i $subfiles_from_objects -new_folder $objects $oe_path` and `package_update.py -rename $oe_path`. Manifests are not updated. _sip_log is updated but sha-512 in both manifests.
Changed:
line 243 - if args.aip:    ififuncs.checksum_replace(sip_manifest **_sha512** , new_log_textfile, 'sha512')
relative_filename / _new_folder / _new_filename = ?.replace(<s>os.path.dirname(args.input)</s>source + '?', '').replace('?', '/'))
args.input == path_to_oe_number
``os.path.dirname(args.input)`` -output-> '...'(parent path of oe)
--> ``?.replace(os.path.dirname(args.input) + '?', '').replace('?', '/'))`` -output-> 'oe/uuid/...'
``args.input`` or ``source`` -output-> '.../oe'
--> ``?.replace(source + '?', '').replace('?', '/'))`` -output-> 'uuid/...'
Manifest …
=> package_update.py - fix relative file/folder name for move & rename files

scripts/batchsc_aip_update.py, scripts/rename_objects.py
update according to special collection requirement
=> rename_objects.py - update trigger list, apply for all subfiles; batchsc_aip_update.py - fixed bug for error_list

scripts/deletefiles.py, scripts/ififuncs.py
Update SHA512 manifest for AIPs.
Terminal:
```
deletefiles.py -aip -i /Volumes/Scans/3_minute_yhe_test/88b6e125-f83d-450a-a458-1e0187a63f6b/objects/123.jpg /Volumes/Scans/3_minute_yhe_test/88b6e125-f83d-450a-a458-1e0187a63f6b/objects/Copy_of_123.jpg /Volumes/Scans/3_minute_yhe_test/88b6e125-f83d-450a-a458-1e0187a63f6b/objects/D4106.jpg -uuid_path /Volumes/Scans/3_minute_yhe_test/88b6e125-f83d-450a-a458-1e0187a63f6b
Namespace(i=['/Volumes/Scans/3_minute_yhe_test/88b6e125-f83d-450a-a458-1e0187a63f6b/objects/123.jpg', '/Volumes/Scans/3_minute_yhe_test/88b6e125-f83d-450a-a458-1e0187a63f6b/objects/Copy_of_123.jpg', '/Volumes/Scans/3_minute_yhe_test/88b6e125-f83d-450a-a458-1e0187a63f6b/objects/D4106.jpg'], uuid_path='/Volumes/Scans/3_minute_yhe_test/88b6e125-f83d-450a-a458-1e0187a63f6b', …
```
=> Delete Package File for AIP - deletefiles.py & ififuncs.sort_manifest()

scripts/bitc.py
Issue: logo is too small for high resolution
Fix: add command of scale logo input for ffmpeg command
by:
- separate `video_height` to a function
- use `round(video_height * 0.15 / 90)` for calculating scale percentage (90 is the height of the IFI watermark logo)
=> bitc.py - scale logo by resolution

scripts/bitc.py, scripts/dcdm_helperpbcore.py
Update 1: Add placeholder for ``essenceTrackSampling``, ``essenceTrackEncod_au``, and ``essenceBitDepth_au`` which ingests from audio section in '_source_mediainfo.xml', in case that there's no audio in DCDM.
----------
Update 2: Add selection list for ``Donor``with auto-filling for ``Restrictions``, ``Depositor_Reference``, and ``CollectionTitle``.
``````
......
Please select the donor with the number
1       Screen Ireland (previously Irish Film Board/IFB)
2       Arts Council
2
----------
#or
3 #input a wrong number
Number is not in the list provided! System exit...
``````
=> DCDM helperpbcore - updates
